var htmlConfig = {
    "bookConfig": "v01000110320aBdp7IXiwOfj4HZquCaq5Jfr7DfhzDSswGVmzIbh5Jaj8PSt5MSr2Bch2Hcr8LflzPfszKSruHQnvHYpwKXkwBVn4Eaq8Gds3NVk8JXr5JTi9GShzMcu4JTpyHbu5BZv8HQm6Gem8JXp8LalyJThwEeoyCfhxIem1Mei7Iet6NQr5BWm7Icu0Gfv6DWq1EfmxJekuLVq5DZo6Jah5DWm1FZuvBYvzPaj4Net3ETrwBbvuGXh6Hdt5GXr3Odh6Pbm5IXv9FYkvGTo0HXi2CTv1FWs8JXmvLem8LdtxObk7DbvyIZkuPdj3NQn2CTg2JTlxOWs9Mek4LTq5MXu3PfizLXuyBfh0DZsvNSt9Ibg9GWnuHWg9DWhvEYj2JekzOSlwOTp8IdiwBVkvGcgzMVj8PTlwIVpyGanzAQr0Efq5AWlvKQj5HVk8LcvvFUv8AZvyNbhzBdgxCTi9BYkxNTo3MfquFfq1CUg0GYg6DUo9Mcl7Gci0Leq9Mal3GbovHTqwDZpzGVvyFRhvKRvyBQu4PXqwBYt7ARkuEdt8CQl0OamwEdq2ATlvJblwBRv4FdnuLSh1DWn1Edj3BSo9KYj0Ofi9Aft7BXq8JVuvGUruLSi9LQvuIZmxDWg6FcuvMdtzLcvzPav3GRn9Cbj9Nfv4Efj4AWixEfgxEWr2HcozGRm8LTm4PcvwDWrwGYn8EYq5KbowFYn6KTq1PcmyOcn8JXszATu8KSr3DWo6HVvzGWkyKZs9IQtwMct2HTk8HekxAflvCah3AflwIcg7OSluLQpxBXqwOQk8Oat1Oev0JXl8MSo8EZgzAZs5DWi2MRi1FVrxFQr1PXt4NWt1BUozEThvNdi4GSpxFUmzGag5DRlzOdhvBUs4GSn6FTj1Acv4Bbg0BRh3LUn3KbrwJWl5Hdi1Mfo3OSmzLRi8PUvuCRs4Mbk3NVi6IZh9AXr3ASrvBaqwGTlvEYh2Efn1LRg7KVnuKXj0Hfu2BUi7Efn9OWq2BYs4NaguLdp3CTh4JZswKRnuLRk0PXr5McquPav7Act1AQj5KXnvBZtxAbv3PYr9DTgyFTs2LTs1BVm4AaowHanuAakwJVvvPRqzNdq7FUp5LUruPTt9LQp2BQj1GTm3GXjyNcs5EXv4LdgxJWk1FZrzBen6KRjvJUv4HUj7FZqvLQmyEei8Mfg8GXsuEVhzNcgwEYl8LcsvAZvwBajzORtyLepuJZn8GerwIei3LUtuPWnyGVl2Icm9Ceg2GQh2GTn0IUhwLRt3DTi0JbuuFXn9JZr4Kcg1PTt4GSh0Ier4LTg2OYv3IXq2JQp4CRkzNekxCaqxIck6LSi0GcivNZlwGcn5GUswIcv3KenvHSpuIQjzHUhzKal6Ebm4KUuvCSp4KQt7KYoxDQvyKdnzCWp1CZi3PXs2LRvvDbovIat1GZj7Mcm0Mbr9KXk7OYvwDbjzFTo2Kds6Ddp1DanvPZr6PXl7PZl2NXh4PbqxBYkyFdsxIclyBYivNZi2GYq1MVv8JclwKTu7BZqxBcuwNeluNfmzDfs2NZszEfg7Ddh4IZh9GQh5GXu5DYq8Ffk7BdsuAZrwHaj8DUgvERm8Icn2GagvPRn1Nds3PcnxDUtuAWi5Mcg9Mcu1KXr2GVt4BZg6FRk5JWsvOTp8PctxGemvNXlwEQruBWq4IVqwJZg2MZkzLVlyEXkvDcquPchwARv8Cdi9Fdg9FXs0PRrwJXn3FRu6NTmyMTo9EXj8Bcm5LXuuCbnvOTs5Ici5Mfi4NahuPai8Pbm0NZi8GQh4CVg3Iai8FUv7FepzCbr6Ber2NYiyEVqzLZiwAdmyIUj7Kek7Aar8ETv2Ieo9CRpxCci4MdgvBYl9Mel2Hdi1GWrxASpuPTl5PQv2OXtxMRn0NWk8Ocr6JTtzPSg0OaouASm9Gfg9NanxLZi2PXl7HRp1PRq0PZvuMen7Abt2Nfn2NWiuEem1Ncq4CVlzFbo4Mbv3Afs0Mcm4GamyBVu9JUjzHQguJct7OWn2Hbj9Fdo2KRkvGZkyAdlxASj2Eel5EXs1ETt5PQnwDesvLaoxCUu9Lcv0JVg7NVqvBdg5CVjuGUpyHSt6OWv4ITnvCQvvLbk3AXk6MXtvMWivOQp3NUswDVt2JRq0HRl6Afu7Kdr1CUpvGVnzMfr3CUt0EWm4DbqwHQn6BTr2Iav6LWn3Cau2Jcn1JamzDXp2Lau8Ldj5LfkyKdqwOUi6PfkwPbjxHTr5Ffu8PSuwObu1Pfi3GfhxKWo6ERiwJSlxHXjyHeu5Icn8IRt4GduxGZs5MfquOes2Dav7GXlzKUh1KXuuNRi4MVoyFSlvCas4KcnxLUv1Pap5BXpyIeovDfo4Jeh4DXt8Fek6MRrzLVp4EUtwCSi5EclxJWi2PUi3Aau8KTt6IRl0KZqxESu2OSn1Idt8IUh0DRhwFcl2NVv7Ofk7OVrxHdpuLYswEcs5GYl4ASpwDQnwEQs2Mbi6Lbq5KXi6Mal3ASg2KXq9Icl9HSivEcl7Gdm2Jcq3EWr8MYvxBSl0HXiyEQh4Cfp9NUr4JUn5Nbv7FQk0Hdj7IRowBShxFck7FaluFYt0PXhvIRgzDQj3PcqwCQq5IWg7KWo8OVn5NalvBXjwISi4Hdg8PZq7ITs9Cep3CTuuFUn2FUv2ARt5Jcs1NaluGRtvAam2Jam8PcoyDZgvLTk3PctzDWpyIVk8OSivFZh3Cfn3CQovAel2HamuOTt8NVn6FSvxEehwPTl2OWq5NXj0KfkyIbn1LWu6EZp6LZgxLVhwETs5EcvxEdrzIWtyBdovNRg0Ifm4FXlzEci6EVh3PThvFQkvNbq5MYh0KQmzGds1NRnwNQv2GXl3Ceh5KcuuDQruNXv2JetuJVvwKTtyNXp1Beg2ISs5Naq2Cek0Pas0Ifu7Bat1MalwFdgzLbh6Eak8Kbo1Nbn9Ccn0JctzORkzBRuwKQk5AVv4FVn2LclvMci2Kfk5Gfi7OakxMaiuDQt8CXg3EatuMahvLRq6LVt9Mem6MTpvKYluIbg3ASovHdp7AXj4ObsyJelyESp8CYryMei2Abu6BQvuGdr3Jfk3Mdj7DXg6Bbt1PWnuAUu5Kds6Bdi7OWh8Fbr9HSr3CXi6GWmuKfruPThyISu5JXlxKbs6MRoxEUjxJcm6GduwCep2IVu1DYgwEVl1Iaj0NTv2Ncq5CRt4PVq0Ldt2OfmxKaq5IZr0AXq2GYm0NRm7GYmwEcl1JUkuHQqzOem3PXh5EZizFaq9NSnxAbt1KfjuHeuuFStvKctzMcs0LUqzNdu2PdswEYs0PRv0HUp3FSrzEYg2PchxKZv7HSrxARiyDSlxBWh3GcgxBfj7EXkuEdqyOTlwOVs1AZu1BRv6ISl0Hfp5OTp2KQt7Bdq9DTt0AdtyKUl8OZr7ETvzCav6Jbs9Dfg6DTj8MXo9LSmyIbpwBbmzPVk1CXuvFWnwAQn9MfpzIeuwJRizLdk0AXovMYr0FRguLYqwFXj3BWpuKdryMXh8MVi6BYrwKRnuOWowGRhwKbowISs4Ofg5KQkyKXt5CUs8LbizNZg1EerwFYv0Deh6Ccr3ASgwKRuzNQuvJVl2CVn6GYk4Kfh2GUqxKYrzJQo6Iev8GZo6BXtwDfvzNThvGet5KYu8Aav5OUowFfoxKUuzLdr1DUuwMWqwAZq4MTt7KTg1FTv8Bcl9JeuxHft1JQiyMdgyOTj7PZq3JYo6DXu0GSu6PXouIQg5JWo6CWpvNbn8NWrwFaowOWn1Eaj3AQj4Eau0Gdp7MRquGQtzGZr1DRp1AXvxFXg9FWmwMds9AQj5LZqyKWjzCbruKfi6CQm0Oen2EQg8DZp7MZn9Pfp2EWv5EcoyLbjxKQl8AUgzMbouOfvxOVjwGSo7Ges2GVrwFaqvMYl3FarxMYu7Cfu1BenvMWq1Dbo1KakwKUh8Cbl2Eai9PUi7BchyFRruFRj0Jat2AYiwAYszPakzGemuIQt5EUiuLav8Gav8BauvEWn8IXs4CbpwHXpwEfsvHWg3LftxJSj5BeswJQg3JctxAUm5Jfi1HVv2HetuLWr9GUn2GXvxOZswISr3PajvKRl0HUr3ORtxKfj9HQg7AfuuLfs1Ael1LemuGah0Adq7AYpyHSruDevvIWguHdkyBfp8Fbp0FWi6CQk6Jej8Mbu8MZqxGTlzIRn3Ibm3DZsuFXk5OVs7BfkyEdp5CfsvDfl4AZg7Mcp1Mch1Hfr1LYgzGfq0AdpxCVouMbk3EekyOcowCYt8KbpwPYhvCerzGbk0Idk1JepzOatyLbn6HWswIVj3BTr1DTuvASk0Kfk2OTh2BToxCbswEch8CUgwMXo5HQq1CXg9JWixMfp6LRlyNRp5JUv7CTh6NWovEVu4IXj9KTtvPdsyIck5LVv9PXuwIWu3HVn1NYq3JZg3LUk1KVo8ERk9MVtyDZo6FbiyMctxHXhyPSh8Hbn5Jcn4AZh8DWk4LZs2BWp8PZmwIYouBRn4GQl7KYr1Bfh1FblxCZu5Mfp8GclzKfiwJctzKcm4JTkuNTi8BaryGeqvBVn4AWh6OQr7IQt2ParwBam9Neo9EZn5KUn3NQp5BXq5FdkwFeqyKapxAWszFQswBSlwPar2OTk9CZhvMen9NbhzLQj1MTi6Cau9ETh7GVuwFZjxGdj2NUrxPfruCbo9CfjuJQuvFXp0DVt4Oau8FVj2JRlyAXm1OZm8CZgwPcv6Afm2Kap7CZv9MYg6MRm4OQt5ITm0PaszKXkzNRr8BdmzBUt5MSk9GYt8CUk4FSouHZo2LQowNfvyFah9BRkvDYh0HXi3ISl3HXo8IRg4Ldk1PWtyBYs4BaruMZsvGVgwKesuEek4Ceq0PcuxPRn0GQo3EVjvCWpvDRmvPZhzNZqyGah4OdhwPdl4FYh8EWt0JSl5EXmuKTg4GSh8Aal8ORoxGdg6PTm6LRi0PSn5Fbt6GVr1FUi4MYh0MTmwPVq0CVl6LQu2AYgyLUl1ORn8MYk6EWr5Ldo3KZv3Gfo0FWhzKau2CXg8AUh8BQq0EdmuIak0GTpvHchyDYg2IXo9EWv4OQt2PfvwPXh9JQv2Nbv2MSo1FSsuMUruCYi4EYl9OUk8MbluDcjwGehyIVl7KUkuATg9PVgyGer3Ccp7Fem5ERt8IZg0NSm2NWovPRl6BZh1MeswGep4Mfl4JTv4NTowJfr6Iet9BQs9AauuDYozAdlxPZp9PdmyEfu2Jfh5DUvuASvwMZu4OYovAcmyFRk8ERm3PSpuPSr9NSsxCbt0Cdg5LXrwCdp8DVu1OTl0AbiyHYv6JVpwMds5Fcr1Nbr1OQv8IRo8GSj7HTl3KZrvLTn7Bbr2OYnyJZl4Ndn0OVl3IVgxIfq5HevvORruBSn1JYo2DTl9DXq7FcvxHbu5KSo3HagzFUn6BYv9HYq7JTvxKeg7NSk4AWvuAWj7NXj1KZpyNTo8LVp0BRrxKQh4BVp4GYl1Bbq2Bcr6DXn5JSk0Pdh5EagyHcqvNdgwAUg1CTu2Cdi5IUu4BQo6AQnvGasxAZmyAQtyJVuxMbp4Lbv9LUp3Dcg5KckuMWp6MfsvPel0HZq7JZp7Acg1GfkxPVl6GQiwLVruBcu2AZuvBZnvCUr9DTluIViyHRh9BVj3Ldj1AZt6NQo9LTrzNan8Nav9LaoyAYl4JatvJZm1LXrzDdt9PWt7Nbu2MZv2BeuyLfs0KVl3NSp7GVh9Lan7MYp1Bbn5DdnxHWkuDctyGUh0Obq6JYqzCSm6DQhuPVqyPTs7JRjuPVl4CYluHdo2FTq8MWg3NYj3DSk9BVo1GXuzKYq1NVvyJcr2ORk5AWpvLXv2MSi8Iag9KemzGfswJUv1GQj3BZk6Eer0OVovLUqzJbk1JVl0Ndg4GSk7Cdq3HTl7Kdp3AQvvAauvMTjzIak2PSm0KYu2Ffv9OWkzPUrvLQq4JTu8FVvyHaozNVp6PXv8DZp1DQs5HQs6IWk9BSpwNXtxKQq0IRg1HTpwMQp3Cai1Ecu1HXl4MZg9HehxKbi3Ceq6Jdn1Neg4EVk4Odm8Gbl2LVnxKfv3KTg0LVuzParxJQmuHRrvDYv9DSpyNZm0PYt1HcnwEUn5CZv9Bcq4PWgxOej7OQk4MaluNct3CUjuCfj0MYovLVhvMeg1DTh7Mdn5Nbh9GQm0Neo6Pbi6Dds2MUg1CXp5CYr4HWr4PYtyGej2PbuzNWovPUm0HUj7BYm1LQi1JeguOXh3IdnyCUm1LRu8LVs9Jdn5ESjwOWj6CXn4OQoyFYl0Bbs7HcvuObj5Pfj7BRvzFcozKRiyGWpuNVl7OYszFcjwMVnvNXuvDTi4PSuyNTj8GfkvBUqxLRu0Bck3CWmvFWixBYpxERjwFZivEVq7FRp0LYvxAYhwFRlxPeg1NTj0Nep9Dei1Feg2LTgxHci2Cau9DenuOTj4FZvxKZjvBUsuFWquFfjuDbv0BRguAYtxCckvLQh0JQv9BbiuKbg5PSm8Bet0MZu3MTv1LTrvMSuyJVl5DVl0JeuuIasuOTn7OQp4IWr3BanwMel6JVj4BXhvJUv9JThvJemyDdv9Edu6EUuzLVv1ERuuCfouDWu5GVu9KRtwJXjuKYh5FSu1Ifm6BXj3KYq1FZu0HVp1Ecr4BTt4HSj1LYn6DdjvHTl7Kfv4PQj3ITqyBWp5GRjxFQvxPTtvMSt6HRq0LZuzLZo0KbovCcvvPQmzFVi8OTg5Nfk9GTt4JRryIeq0MWuvCWn4HXgyNaguAQt6Hdn8Cdv3DYnyPfu7BUn4IetuESn9DUm1LdvxBWpxMfs1JdtzEcn5GajyGRu6FalyBUj6FVp9IXi5MVo2AcoxHUq4GatyLbn3Ofu2KfmyFVqzPfm7OTn0Oal9Bao3KWj8Deo0DWn1Gau5Gdq7GfuxMbiuAXkuGSu1JSs0EZl4OXm7Oco4Jem9IWj2NTt8Jal7Acu3KXs0Odt0LQpwMdr7LXn6LdrwGTs9Nbr2DSq8GWm6BbjzBTtyCWvyEXj6Pfq8IYq6OUq8NYu1FSnwLdhxPVi6Mei3IagzHUj8GSo6AZmyJZr1LZi4JatzFfiuBTu4PTgwBVm5GYq1OTm9FblzLWm9IbhwJWr9FZh1CfgvNQg7LZo9JYo7AYi5NQp7NQg5GQi8CRh6HRg5JWo0Nbj9DfhyAQv4GRjvBcg0GVjwDQo5FZsuOYj3LUm4Iag4OWi2IYhxFWi4KdovFWs6Lbq1BTj2IVh1Fdp4MfqwOTgvLUnyETnyCRg9NWv6GRkzCYo9OUk9CUg7Oek0PSqyPbs6Eap0Edu6JYtuFfgzBYnvFTm6LSp8BTl2NTq3AVg9MSkxASj6Lcs4EWs1Aan7Pbm0LQi7LfvuMVouEUh8Bem2ORl5MRi3Lbj6JYhxDSj0Ffq0EYhyLVg3KQh7FUhxBbp4MTkvFVv1GTuyJVqwHVtwHfszJck2IZnwAfr8NXk8KXg9LWk5JXr7EcgvAZh3CWv0IWj2DSs5Jfq4DTk9IfivNWm7Pfi4HQpyOSk4OUryAdsyFfvxMSj8FajuBUq3JRkyEdv2IaqvNRlzDUq1ASp0JZq0Bbm0GQg1MUl0EVm2Pcs3IckzBaswHSivNYlwGRuwBUuxNWrzMeo9JfgwIRt1FeouOfv7LTm7OUt7LfluNTh0CTs4Bbi4MfowEUrzJbm2MYmyDThvDZu4ORn1JYg1HbquLWqwAXv2EXl2JZlxHeo2GRguBcpwFWuvDZk0Jbi3IVr4Ccl0PUhxMdj1FWj3LTs4DTg3FfqyISvxEcs9Kam0Kbn3NQv5HerwNet7Jdm9Jbk3ARs9Kfn5Afk7OZu5Jas0JesyJWi0AWi7Cen8LZu2EYr3ITqzOQtyAUr1DTgwHdl2DbiyPVq8LfovNUjvKXkwCfm9FdqvHam5MYswASt5NYg7ETp8CatyLYqvGYkxMTj5DbpyKduzBesuPbp6EajuJRt9EXiyEWqyCbp8Naq6Edl7Hck2Cdl3EXi4KZh2Adk5DdjyPZsuMeo9Ccs4DcsxLfk3CcmvMej7Mbs8KVl1MblzPSmwLZnyHSuyFTj5LTs0AYswJStvDQvvOYr5Oaj2Nds2BepwLUgwBXrzAXq0JXgzCRu0CVt8Dfh9Dbv3OSm0HQsvDQhwHUsxMSl3CUkvMXk0PUv3Nau2AeryEbt7MWv9HSuwMar3Ffg5Ieo1HVt6OSmwLUhwDQn6HXn0IQm3MenwNRi1Ldh7OXi8DRrwLTm6CciwHYnxMZtzFcp7OWk5HVnxOUm2Pbg8LemxIXk9Net1BSp9Nds4CYo9ATuyMZryLXtxMXnxNejzIcp3JbkuOfo5Jbo3Bdh6LUrxGXk3OegyNVl6Ffg4IZpwKem9MSp1HWp3Pcl5DRr8OQq8Dct5Mah6PXr7IUu9DSr0CTi1Eei8FQoyDXvxAZjwFdt4KXp9AflyKevuPVi0KdkvDeovARo6AZg0EQm6NXkyJUlvAdn4PZp3EQgyMfjyGbu3FVszFVk6HYkuNRiuITr4PUt7CcpuOXv3HUj0BUs1HSu7BWt1JRr5OVk8DckyFTiuJfkvCYmyFVrxHcmxMaj0MZs6Ofo9EUj0LTlzFXmwDSv6JWj3IevvPRquATk1HYpyKUu2Obq8ERhzDYtxJTkuLenzHfq2BVv3Jeg6DVvxGXo7HWlxKYh0Bbv1Lbg4Kdt1IUmwLTr0Ebq8OaqyCSl6LYg5Jfk8Kbv2BXn4Ebu3PWhxAXkxJWgxGag9DftuOXlxEas3EYo3Ieq9MRv7FasyIau5Abs2Ceq1AYu9LWiyHfvxPWp0PduyLRozNdi2Hdk9Ncl0GRg6HRn8Fdu8KXr6FTl1CXjyMYqzCdp4AWj3Abg9GXrzIQq0ASi9HboxISnuNTuyFWqzJQruBQk8Beo6OSj1OWnyMaovMYt4OfvwGYv0JVj6Fbg6HWiwPbr4Fcs6Ofr6DUuxJStwDfj2Nft4DYvzFSuwBbj1Hel3IVlxNTrzCduuKbi1PZj3Gch3BVt4LZpuAat4BUg6Met2FSu1GUhuOfs3Bak8Mdl4DYuvCUl1LRn2IXl1Jfs6KbhyGZg4Kdi8JfovNRpwNWl3OZguHZpyJet9PfizCTkzMbr5BUhzKSryKVlzDVnvMWh4DXm8EXkyDer1Nek8LVqzDds9JRp7AYk6Pds2BTo6CTl3LVm4Mbj7KVu7FVhuPYryHQg4CYrzBTtuMdmxHbi8Iah5Gbt9BYl9GYr9HXgxJWmuOYu8HRp1AVi0DSguKYs3ERjvKWtuBaouOYk3JckuJTuvAfo6OUguEdl5HVt9JXiuLUruFQquCbg0HUrxGalyJXq9Jag5KQo8Gco4JUvvKTr9EXr6Nfp6IWq7IXu4FQjwLQh4LfiwGRq7EYp4FanzFav2HSo5Eet5LVu7JcvzFehwAcl0JRtwKUt6Dbl2Mfq9HShzKWj2IbruNaouEbhzNdj6KXlyEWuzOYu6LcqxLai5Cfp6HYh2Hbk1Abq5Bal5DSr9CVlyBQi2Lav9Oar4HeovDTpvMXi5KWg1PYszHeh6ITqyHThuDTvzNas9FRs5HUouBXt0DdlvGSs3LYg7BYg9BZg8KVs2DfuuJao9EejxJbv5HXo4Ocl6Pfn2Neh8Obo4HSkvCcg4KQsyBZiuKRhuIXkxIVs2GYsyETl1Kct1Ibs9BeouDct6LYuvMdmvIbn8ASo2LWiuHbm2PSsyOTn6Bdh7KSj9NelyLStxGVhuDetuPeh3MVmzHem6IVk6BVt5KSu1ARm1ISgxOeovGTlwCat0FZmvOQg3KboyKequEUsxOZj8NZp3BYr2LQo4IfvvJRvwCQn1Afr7LVn7GSj6MTrwATv8EclvMTo7GRswIYo3GYg4Kfq5Iev1NRpzMcj4PYm7FYlzFXn1NRv2Pfv1Lcg1LRuzGSu3GehvBav0Hag8JQg8Bbr8IetwMeo8CWrvBSk3LQm8Gas3KUg6GUu0Ofs6IXm6NfjwObs1DRh8HelyKah2JZs4NevzCdjyOSiyAeq7OTixDYg7GXpzCWm7ITsxPbp4BVt7GRn8FdpzGStuBZr0FSizCev7KSrzPeh9Gat2BRs6FfgxDUpvHdm3PRouPYt9LZi4ASjwEWq6PQovPfszMev9JSvzCSk1Dam0KRq9MXoxKZr0GRq7Ads7HUk9HXhzNQu9JSq1CVuwAUm4MaguLTp9Ndv7EUq4Aar8Neh1PVtwIQs1BUtyEVo8CfjuIfrxBdo8Bfr9GQi3DVu7MRqwOZqxATuwOcnzKQiuIbo4AVq7MeryCUo2BTtuASp4JRm6HXu9DRgxEYl4GWk8HYv5Dam5EdlxKQkuPRt4FTg3Ccu3FblxHfh6FcvvNcg4Fbm6KQk2FSo2Bfj0Hcr1EfpwCRo3FVu0EWgvAUm5EZlvNYo8MSm4CXt9LYmwNRryLZk9OXkzBWm6NSo3Gfo4MQvzCYm1FYh8Hej7BVh2JUguLZg9CUo5DWk1KWm4NciyEdmuPWk7DXu5KZl4ESt5PRkyJZovJRm4LSnuKSg5AQkxEQv0Jbn8LQj4HTjzFUn8FSo1MTpvESs7Kbg8JTm8LUq5IWvvLds6NelwMStzNdg2Hct3Jbg8NRn8OQu7PXt3CSq6Kal4LWpxMem9LVgyIZi7DRq8DUvyAdsyHStuCYq3BWnzCZg5PUnvNcu8Edo2FTi2ISnzIZsyPUhuOUgvPbr3ITkyHWtzCcquIbs2NRm8Ldl1EZj8JfhzObh4HctyOUm5PRg2IWu7PehzIdvvDQl0BVu5CbpwJVk2FXl7Mdq1FYo5JctyLbizFTi9Oar7Neh0JZv2DXq0BYr0HQlzMSk2PUp4OSq9Hfv0BUm8OXn5HZj4BUpvCUhuGUq7IQn1NfrwEQh5JdtzPcr0KXmyCan3PTk8OcjyKSq4DehwFTvyERl8DXo6OTm2LdoyLWv9NWvxMVl4MRk6Lah0KUl4Cem0FYpyOak9OSj4Mch2HflvMSpwDbv0BduwHamuETkxIeh8KcqwBep8JThwOVi8Edk5DYmyNWt7DQm2Jbv8HXk0KTh2OThuEXj5JTr2HXuuKdm7Bfp5CSr9Lct7Bej0DWhvNXr1AVowKdk4Mcj9LZs3CcrvLZgxAfqyHcivNZn3PQj2Cam3KTtuEZkzKRv4MWkxEXpyKRk1Bdv1BWpuLYl8Hes4HQmuLdqwOXs0EdjuKeq9PUiuORq1IRn8PYj5GaqwGTqvFVn9FYr8NfrwCUk8JUv3DYlwGWk4Nbv7CVn0GRh9EWp6MZq8Fcu0GaowLWhvKdqyCWvwNRuzAUo4Cdj3IYq6Hfg3LZlvDbp1Aeh5Dat2PQhxBYn5Jbr4KRkxNcp6JSmwAcu9MenxGRivDcsvGbjzMVo4Edj8IRj6PQr1HatuHao1CUl6EQv9KZr1LQrxHRswMds4NYq9JZo4NQo7HRr1Nar3GRtwEdpzEQs1CRm1Deo4GZkyFdl0CQluHftxHek7MQtyDer2Neo0LWi8KSr5NYv6Bfo0MThyEfnyCQpuGSlzCWr3DXg0AbguBaguCSu2LRvvJcm7OcixMYhxOfswFbpyHco1LZv5Bei4IQt0EVuuPeovEetvNXs3MWtxMap7MSu0LYg0ITr5Bek0DZlyERrxESr6NXqyAcl3JTm3IYk8CVivCZoxLfh7KatzMTlwIRk1Eev3AXr5AQguAWrxHRu6KXh1ObszDQs0Hck2BWu1CYt0JQruERu4BYu0JZuyOfj1LVhuPYhyFcs5KXqwGZu2FYv4AWi3ETgwASmuNVgvJXnvPUvvFZn1PakxPfrzCYjwMQg3BfvyMQnuJeg0GTi4EUj2KZjxJWrzNbqwBUt7AVp9CUj5BduyHYl5EWl8DXi6ETv6CVn7Lcv8Ncp2KaoxGet3EUp0DXs3AZhzLSh9Eft9Ocv0Ffr5EUm9CUgwPRh9IVjuLTi4Kdh6AQrwATrvEYt8Aeo1HWqxNWt5Cap4Hdr3IfpwOXu7DUp3GYl0Ich9Gdn3NXp3BSpxCSj7CRi3KemuGbn4Afn1HUi9CTv6EVp4NeoxFXquKUu9Kei7OYr2Afg7Mar4BXkxKWr3Hfn7Kfu4AemxLct3GUvwBbi8NZq7FbmuFSm1Oes5GWozEYo0FQtxESlvPXn8CSm3Mdg6EdqyGdh2AUrvFXu0JVs1ITn7LWhvMVq4GemuARjxERlzGRv9Adn7FRk5AUi9LYt7FSq1BYo0NQouFcq8LbuzDVs9KTk1Gfq0BSi9LRu2Pav5Odp3IXtzDTo1DWi4FVv9AXv9LTlwLek7GZo0JXr3ObrxFUi3MVvuHctuOSmvMbs7FTi0GTj9IUg3EZg5JYkyNen7GUkxMetxCTk7JSlvETk6DVnwJTh7HTlwGWv5EbnwDXm5PXo8GUt5Acm9Oas2Odn2EbqyJekxCdr9HWv0KWn8Pch3DbqwAas2JYm5KRs7NZh2AXi5KWo1Hco5KXn7KchwLRjwLft2NWp2FZk7Ick9Eej7FYv6Cfl2Eer0PRlzLepwASj6EWt5FWtxJRpyNTt3Pap9DRr6GboyLTi4GRu9JaruGZrzFcp3CVv2FTt6BUjwIWt1EWm6KRq5EbhyJUo8Ial5IUr8GXm6AThvAVhyBfjzFWs1IQpwASmvAWs9HWm8Efq8NXm5MXn2OWq1ASnyOfv9CdjxObn8HVrzAfu0Gbs2FbsvAWkvEdv8Cft0MYj9Cdg6Aeg8IfpuETk5HUhwFRpuPYn7OVo5GegwMfr1Nbh6FXs2EapzOdg6Gdh3ASr7OZvwLZv3IfqxPXo6ETl4FRmzDZmvFTk1EajwHXmyAs57a1c1982c72e0d5169abb9d3515a05e20",
    "aliasConfig": {
        "appName": ["", "", ""],
        "totalPageCount": [],
        "largePageWidth": [],
        "largePageHeight": [],
        "normalPath": [],
        "largePath": [],
        "thumbPath": [],
        "ToolBarsSettings": [],
        "TitleBar": [],
        "bookTitle": [],
        "bookDescription": [],
        "ButtonsBar": [],
        "ShareButton": [],
        "ShareButtonVisible": ["socialShareButtonVisible"],
        "ThumbnailsButton": [],
        "ThumbnailsButtonVisible": ["enableThumbnail"],
        "ZoomButton": [],
        "ZoomButtonVisible": ["enableZoomIn"],
        "FlashDisplaySettings": [],
        "MainBgConfig": [],
        "bgBeginColor": ["bgBeginColor"],
        "bgEndColor": ["bgEndColor"],
        "bgMRotation": ["bgMRotation"],
        "backGroundImgURL": ["mainbgImgUrl", "innerMainbgImgUrl"],
        "pageBackgroundColor": ["pageBackgroundColor"],
        "flipshortcutbutton": [],
        "BookMargins": [],
        "topMargin": [],
        "bottomMargin": [],
        "leftMargin": [],
        "rightMargin": [],
        "HTMLControlSettings": [],
        "linkconfig": [],
        "LinkDownColor": ["linkOverColor"],
        "LinkAlpha": ["linkOverColorAlpha"],
        "OpenWindow": ["linkOpenedWindow"],
        "searchColor": [],
        "searchAlpha": [],
        "SearchButtonVisible": ["searchButtonVisible"],
        "productName": [],
        "homePage": [],
        "enableAutoPlay": ["autoPlayAutoStart"],
        "autoPlayDuration": ["autoPlayDuration"],
        "autoPlayLoopCount": ["autoPlayLoopCount"],
        "BookMarkButtonVisible": [],
        "googleAnalyticsID": ["googleAnalyticsID"],
        "OriginPageIndex": [],
        "HardPageEnable": ["isHardCover"],
        "UIBaseURL": [],
        "RightToLeft": ["isRightToLeft"],
        "LeftShadowWidth": ["leftPageShadowWidth"],
        "LeftShadowAlpha": ["pageShadowAlpha"],
        "RightShadowWidth": ["rightPageShadowWidth"],
        "RightShadowAlpha": ["pageShadowAlpha"],
        "ShortcutButtonHeight": [],
        "ShortcutButtonWidth": [],
        "AutoPlayButtonVisible": ["enableAutoPlay"],
        "DownloadButtonVisible": ["enableDownload"],
        "DownloadURL": ["downloadURL"],
        "HomeButtonVisible": ["homeButtonVisible"],
        "HomeURL": ["btnHomeURL"],
        "BackgroundSoundURL": ["bacgroundSoundURL"],
        "PrintButtonVisible": ["enablePrint"],
        "toolbarColor": ["mainColor", "barColor"],
        "loadingBackground": ["mainColor", "barColor"],
        "BackgroundSoundButtonVisible": ["enableFlipSound"],
        "FlipSound": ["enableFlipSound"],
        "MiniStyle": ["userSmallMode"],
        "retainBookCenter": ["moveFlipBookToCenter"],
        "totalPagesCaption": ["totalPageNumberCaptionStr"],
        "pageNumberCaption": ["pageIndexCaptionStrs"]
    },
    "aliasLanguage": {
        "frmPrintbtn": ["frmPrintCaption"],
        "frmPrintall": ["frmPrintPrintAll"],
        "frmPrintcurrent": ["frmPrintPrintCurrentPage"],
        "frmPrintRange": ["frmPrintPrintRange"],
        "frmPrintexample": ["frmPrintExampleCaption"],
        "btnLanguage": ["btnSwicthLanguage"],
        "btnTableOfContent": ["btnBookMark"],
        "btnExitFullscreen": ["btnDisableFullScreen"],
        "btnFullscreen": ["btnFullScreen"],
        "btnHome": ["homebtnHelp"],
        "btnMore": ["btnMoreOptionsLeft"],
        "frmToc": ["btnBookMark"],
        "frmSearch": ["btnSearch"],
        "frmLinkLabel": ["lblLink"]
    },
    "meta": {
        "htmlTemplate": "Popular",
        "theme": "Default",
        "title": "KG MENU",
        "description": "",
        "url": "",//"https:\/\/online.fliphtml5.com\/ttkai\/qgfi\/index.html",
        "pageCount": 34,
        "pageWidth": 593,
        "pageHeight": 839,
        "template": "Popular"
    },
    "project-config": [],
    "bmtConfig": [],
    "videoList": [],
    "language": [{
        "language": "English",
        "btnFirstPage": "First",
        "btnNextPage": "Next Page",
        "btnLastPage": "Last",
        "btnPrePage": "Previous Page",
        "btnDownload": "Download",
        "btnPrint": "Print",
        "btnSearch": "Search",
        "btnClearSearch": "Enter key to search",
        "frmSearchPrompt": "Clear",
        "btnBookMark": "Table of content",
        "btnHelp": "Help",
        "btnHome": "Home",
        "btnFullscreen": "Fullscreen",
        "btnSoundOn": "Sound On",
        "btnSoundOff": "Sound Off",
        "btnShareEmail": "Email",
        "btnSocialShare": "Social Share",
        "btnZoomIn": "Zoom In",
        "btnZoomOut": "Zoom Out",
        "btnDragToMove": "Move by mouse drag",
        "btnAutoFlip": "Auto Flip",
        "btnStopAutoFlip": "Stop Auto Flip",
        "btnGoToHome": "Return Home",
        "frmHelpCaption": "Help",
        "frmHelpTip1": "Double click to zoom in or out",
        "frmHelpTip2": "Drag the page corner to view",
        "frmPrintCaption": "Print",
        "frmPrintBtnCaption": "Print",
        "frmPrintPreparePage": "Preparing Page:",
        "frmPrintPrintFailed": "Print Failed:",
        "pnlSearchInputInvalid": "The search text is too short.",
        "loginCaption": "Login",
        "loginInvalidPassword": "Not a valid password!",
        "loginPasswordLabel": "Password:",
        "loginBtnLogin": "Login",
        "loginBtnCancel": "Cancel",
        "btnThumb": "Thumbnails",
        "lblPages": "Pages:",
        "lblPagesFound": "Pages:",
        "lblPageIndex": "Page",
        "btnAbout": "About",
        "frnAboutCaption": "About & Contact",
        "btnSinglePage": "Single Page",
        "btnDoublePage": "Double Page",
        "tipChangeLanguage": "Please select a language below...",
        "btnMoreOptionsRight": "More Options",
        "btnFit": "Fit Window",
        "smallModeCaption": "Click to view in fullscreen",
        "btnAddAnnotation": "Add Annotations",
        "btnAnnotation": "Annotations",
        "FlipPageEditor_SaveAndExit": "Save and Exit",
        "FlipPageEditor_Exit": "Exit",
        "DrawToolWindow_Redo": "Redo",
        "DrawToolWindow_Undo": "Undo",
        "DrawToolWindow_Clear": "Clear",
        "DrawToolWindow_Brush": "Brush",
        "DrawToolWindow_Width": "Width",
        "DrawToolWindow_Alpha": "Alpha",
        "DrawToolWindow_Color": "Color",
        "DrawToolWindow_Eraser": "Eraser",
        "DrawToolWindow_Rectangular": "Rectangular",
        "DrawToolWindow_Ellipse": "Ellipse",
        "TStuff_BorderWidth": "Border Width",
        "TStuff_BorderAlph": "Border Alpha",
        "TStuff_BorderColor": "Border Color",
        "DrawToolWindow_TextNote": "Text Note",
        "AnnotMark": "Bookmarks",
        "lastpagebtnHelp": "Last page",
        "firstpagebtnHelp": "First page",
        "aboubtnHelp": "About",
        "screenbtnHelp": "Open this application in full-screen mode",
        "helpbtnHelp": "Show help",
        "searchbtnHelp": "Search from pages",
        "pagesbtnHelp": "Take a look at the thumbnail of this brochure",
        "bookmarkbtnHelp": "Open Bookmarks",
        "AnnotmarkbtnHelp": "Open Table of content",
        "printbtnHelp": "Print the brochure",
        "soundbtnHelp": "Turn on or off the sound",
        "sharebtnHelp": "Send Email to",
        "socialSharebtnHelp": "Social Share",
        "zoominbtnHelp": "Zoom in",
        "downloadbtnHelp": "Downdlaod this brochure",
        "pagemodlebtnHelp": "Switch Single and double page mode",
        "languagebtnHelp": "Switch Lauguage",
        "annotationbtnHelp": "Add Annotation",
        "addbookmarkbtnHelp": "Add Bookmark",
        "removebookmarkbtnHelp": "Remove Bookmark",
        "updatebookmarkbtnHelp": "Update Bookmark",
        "btnShoppingCart": "Shopping Cart",
        "Help_ShoppingCartbtn": "Shopping Cart",
        "Help_btnNextPage": "Next page",
        "Help_btnPrePage": "Previous page",
        "Help_btnAutoFlip": "Auto filp",
        "Help_StopAutoFlip": "Stop atuo filp",
        "btnaddbookmark": "Add",
        "btndeletebookmark": "Delete",
        "btnupdatebookmark": "Update",
        "frmyourbookmarks": "Your bookmarks",
        "frmitems": "items",
        "DownloadFullPublication": "Full Publication",
        "DownloadCurrentPage": "Current Page",
        "DownloadAttachedFiles": "Attached Files",
        "btnCopy": "Copy Button",
        "infCopyToClipboard": "Your browser does not support clipboard.",
        "restorePage": "Would you like to restore your previous session?",
        "tmpl_Backgoundsoundon": "Background Sound On",
        "tmpl_Backgoundsoundoff": "Background Sound Off",
        "tmpl_Flipsoundon": "Flip Sound On",
        "tmpl_Flipsoundoff": "Flip Sound Off",
        "Help_PageIndex": "The current page number",
        "tmpl_PrintPageRanges": "PAGE RANGES",
        "tmpl_PrintPreview": "PREVIEW",
        "btnSelection": "Select Text",
        "loginNameLabel": "Name:",
        "btnGotoPage": "Go",
        "btnSettings": "Setting",
        "soundSettingTitle": "Sound Setting",
        "closeFlipSound": "Close Flip Sound",
        "closeBackgroundSound": "Close Backgorund Sound",
        "frmShareCaption": "Share",
        "frmShareLinkLabel": "Link:",
        "frmShareBtnCopy": "Copy",
        "frmShareItemsGroupCaption": "Social Share",
        "frmPanelTitle": "Share it",
        "frmShareQRcode": "QRCode",
        "TAnnoActionPropertyStuff_GotoPage": "Go to page",
        "btnPageBack": "Backward",
        "btnPageForward": "Forward",
        "SelectTextCopy": "Copy Selected Text",
        "selectCopyButton": "Copy",
        "TStuffCart_TypeCart": "Shopping Cart",
        "TStuffCart_DetailedQuantity": "Quantity",
        "TStuffCart_DetailedPrice": "Price",
        "ShappingCart_Close": "Close",
        "ShappingCart_CheckOut": "Checkout",
        "ShappingCart_Item": "Item",
        "ShappingCart_Total": "Total",
        "ShappingCart_AddCart": "Add to cart",
        "ShappingCart_InStock": "In Stock",
        "TStuffCart_DetailedCost": "Shipping cost",
        "TStuffCart_DetailedTime": "Delivery time",
        "TStuffCart_DetailedDay": "day(s)",
        "ShappingCart_NotStock": "Not enough in stock",
        "btnCrop": "Crop",
        "btnDragButton": "Drag",
        "btnFlipBook": "Flip Book",
        "btnSlideMode": "Slide Mode",
        "btnSinglePageMode": "Single Page Mode",
        "btnVertical": "Vertical Mode",
        "btnHotizontal": "Horizontal Mode",
        "btnClose": "Close",
        "btnBookStatus": "Book View",
        "checkBoxInsert": "Insert Current Page",
        "lblLast": "This is the last page.",
        "lblFirst": "This is the first page.",
        "lblFullscreen": "Click to view in fullscreen",
        "lblName": "Name",
        "lblPassword": "Password",
        "lblLogin": "Login",
        "lblCancel": "Cancel",
        "lblNoName": "User name can not be empty.",
        "lblNoPassword": "Password can not be empty.",
        "lblNoCorrectLogin": "Please enter the correct user name and password.",
        "btnVideo": "VideoGallery",
        "btnSlideShow": "SlideShow",
        "btnPositionToMove": "Move by mouse position",
        "lblHelp1": "Drag the page corner to view",
        "lblHelp2": "Double click to zoom in, out",
        "lblCopy": "Copy",
        "lblAddToPage": "add to page",
        "lblPage": "Page",
        "lblDescription": "Title",
        "lblEdit": "Edit",
        "lblDelete": "Delete",
        "lblRemoveAll": "RemoveAll",
        "tltCursor": "cursor",
        "tltAddHighlight": "add highlight",
        "tltAddTexts": "add texts",
        "tltAddShapes": "add shapes",
        "tltAddNotes": "add notes",
        "tltAddImageFile": "add image file",
        "tltAddSignature": "add signature",
        "tltAddLine": "add line",
        "tltAddArrow": "add arrow",
        "tltAddRect": "add rect",
        "tltAddEllipse": "add ellipse",
        "lblDoubleClickToZoomIn": "Double click to zoom in.",
        "frmShareLabel": "Share",
        "frmShareInfo": "You can easily share this publication to social networks.Just cilck the appropriatebutton below.",
        "frminsertLabel": "Insert to Site",
        "frminsertInfo": "Use the code below to embed this publication to your website.",
        "btnQRCode": "Click to scan QR code",
        "btnRotateLeft": "Rotate Left",
        "btnRotateRight": "Rotate Right",
        "lblSelectMode": "Select view mode please.",
        "frmDownloadPreview": "Preview",
        "frmDownload": "Download",
        "frmHowToUse": "How To Use",
        "lblHelpPage1": "Move your finger to flip the book page.",
        "lblHelpPage2": "Zoom in by using gesture or double click on the page.",
        "lblHelpPage3": "Click on the logo to reach the official website of the company.",
        "lblHelpPage4": "Add bookmarks, use search function and auto flip the book.",
        "lblHelpPage5": "Switch horizontal and vertical view on mobile devices.",
        "TTActionQuiz_PlayAgain": "Do you wanna play it again",
        "TTActionQuiz_Ration": "Your ratio is",
        "frmTelephone": "Telephone list",
        "btnDialing": "Dialing",
        "lblSelectMessage": "Please copy the the text content in the text box",
        "btnSelectText": "Select Text",
        "btnNote": "Annotation",
        "btnPhoneNumber": "Telephone",
        "btnWeCharShare": "WeChat Share",
        "btnMagnifierIn": "Magnifying Glass",
        "btnMagnifierOut": "Magnifier Reduction",
        "frmShareSmallProgram": "smallProgram",
        "btnMagnifier": "Magnifier",
        "frmPrintPrintLimitFailed": "Sorry, you can't print the pages.",
        "infNotSupportHtml5": "HTML5 is not supported by your current web browser, please read the book with latestverson web browser. Here we recommend you to read it with Chrome.",
        "btnReport": "Report",
        "btnDoubleSinglePage": "Page switch",
        "btnDownloadPosterPrompt": "Click to download the poster",
        "infLongPressToSavePoster": "Press and hold the mobile terminal to save the poster",
        "infLongPressToIndentify": "Long press to identify QR code",
        "infScanCodeToView": "Scan code to read",
        "frmaboutcaption": "Contact",
        "frmaboutDESCRIPTION": "Description",
        "frmaboutAUTHOR": "Author",
        "frmaboutADDRESS": "Address",
        "frmaboutEMAIL": "Email",
        "frmaboutWEBSITE": "Website",
        "frmaboutMOBILE": "Mobile",
        "infDeleteNote": "Do you want to delete the note?",
        "proFullScreenWarn": "Current browser does not support full-screen,Please use Chrome for best results",
        "btnBack": "Backs",
        "frmVideoListTitle": "Video list",
        "frmVideoTitle": "Video",
        "lblConfirm": "Confirm",
        "frmBookMark": "Book Mark",
        "btnExitFullscreen": "Exit fullscreen",
        "btnMore": "More",
        "frmPrintall": "Print All Pages",
        "frmPrintcurrent": "Print Current Page",
        "frmPrintRange": "Print Range",
        "frmPrintexample": "Example: 2,3,5-10",
        "frmPrintbtn": "Print",
        "frmaboutcontactinformation": "Contact Information",
        "frmSearch": "Search",
        "frmToc": "Table of Contents",
        "btnTableOfContent": "Show Table of Contents",
        "frmLinkLabel": "Link",
        "frmQrcodeCaption": "Scan the bottom two-dimensional code to view with mobile phone.",
        "btnLanguage": "Change Language",
        "msgConfigMissing": "Configuration file is missing, unable to open the book.",
        "lblSave": "Save",
        "accessRestrictedTitle": "Access Restricted",
        "enterYourName": "Enter your name",
        "enterVisitCode": "Please enter your password",
        "enterReadingCode": "enter your reading code",
        "enterTheReason": "Enter your reason for application",
        "enterPhoneNumber": "Enter your email address",
        "enterVerificationCode": "Enter your verification code",
        "getVerificationCode": "Send",
        "sendValidCodeSuccess": "Verification code sent",
        "getVerificationCodePrompt": "Get a verification code sent to your email",
        "enterPasswordPrompt": "Password required to proceed reading",
        "leaveMsgSimilarBooks": "Explore More Books",
        "leaveMsgToAuthor": "Contact Author",
        "leaveMsgName": "Your Name",
        "leaveMsgContact": "Your Contact Information (visible only to the author)",
        "leaveMsgEnter": "Please Enter the Message",
        "leaveMsgCancel": "Cancel",
        "leaveMsgCommitTitle": "Submit",
        "leaveMsgPrompt": "We will forward your message to the book uploader.",
        "leaveMsgErrorPrompt": "Exception occurred. Please try again later",
        "readingCodeErrorPrompt": "Invalid reading code. Please try again",
        "passwordErrorPrompt": "Invalid password. Please try again",
        "invalidPhoneNumber": "Invalid number. Please try again",
        "invalidEmail": "Invalid Email. Please try again",
        "verificationCodeErrorPrompt": "Invalid verification code. Please try again",
        "codeSendingFrequent": "Frequent operation, please try again later",
        "commiteTitle": "Verify",
        "shamStopTitle": "The author's account privileges have resulted in book access suspension.",
        "shamStopSubTitle": "Contact <a target='_blank' href='{%host}\/homepage\/{%uLink}\/' style='text-decoration: underline' >the author<\/a> for further information.",
        "shamStopLeavePrompt": "Please complete the question.",
        "shamStopLeaveMsgSuccessPrompt": "Send successfully",
        "codeSending": "Sending",
        "viewFullScreen": "Fullscreen",
        "cardsSign": "click to view card",
        "frmaboutViews": "Views",
        "btnMessage": "Message",
        "btnInstructions": "instructions",
        "btnArticlePages": "Pages",
        "btnArticleList": "Articles",
        "btnCalendar": "Calendar",
        "btnBook": "Book",
        "btnEnlarge": "Enlarge",
        "btnReduce": "Reduce",
        "btnPrevArticle": "Prev Article",
        "btnNextArticle": "Next Article",
        "copySuccessfully": "Copy Successfully",
        "cardsWechat": "Wechat",
        "cardsTelephone": "phone",
        "close": "close",
        "jumpPageByEnterNumber": "Enter the page number to jump quickly to the specified page",
        "jump": "Jump",
        "relatedContent": "related information",
        "brandTitleUndefined": "No brand name is set yet",
        "more": "More",
        "fold": "Put away",
        "otherWorks": "other works",
        "flipSound": "page turning sound",
        "backgroundSound": "Background music",
        "report": "report",
        "copySuccessTip": "copy successfully",
        "saveSuccessTip": "Saved successfully",
        "scanCodeAddMy": "After saving, WeChat scan the code and add my friend",
        "saveImg": "save Picture",
        "searchTheBook": "Search this book content",
        "historicalRecord": "history record",
        "searchResultCount": "A total of {%count} results",
        "noRelevantResults": "No relevant results",
        "changeTheKeyWords": "Try another keyword ~",
        "leastWordsTip": "Please enter at least 2 words",
        "jumpPageInputTip": "Enter the page number to jump quickly to the specified page",
        "jumpto": "Jump to",
        "foldThumbnailTip": "Click here to put away the thumbnail ~",
        "btnLoadingText": "In loading, it's fine soon",
        "btnTitleText": "Read now",
        "relatedInfoText": "Related Information",
        "brandContactFrTitle": "Contact the author",
        "shareFromPage": "Share starting from page N",
        "TStuffShowInformatin_Width": "Background width",
        "TStuffShowInformatin_Height": "Background height",
        "TPageList_BlankPage": "Blank page",
        "morePanelBookLink": "Link",
        "morePanelPoster": "Poster",
        "morePanelOtherShare": "Other",
        "doublePageTitle": "Rotate the phone to enable double-page reading mode",
        "doublePageDescription": "How to set landscape ?",
        "doublePageGotIt": "Got it",
        "doublePageAndroidSettingStep1": "1.The phone allows auto-rotation",
        "doublePageAndroidSettingStep2": "2.The browser for reading e-books needs to be set to allow horizontal screen",
        "doublePageAndroidSettingStep3": "3.Reading books with mobile phone turned sideways",
        "doublePageIPhoneSettingStep1": "1.Phone portrait orientation lock off",
        "doublePageIPhoneSettingStep2": "2.Reading books with mobile phone turned sideways",
        "noFilesAvailablePrompt": "No Files Available!",
        "reportBtn": "Report",
        "reportConfirm": "Submit",
        "reportCancel": "Cancel",
        "reportAlertBoxCloseBtn": "Close",
        "reportTitle": "Please select the reason for reporting",
        "reportSuccessPrompt": "Report successful",
        "reportError": "Report failed",
        "reportNetworkError": "Report failed, request link error",
        "reportDescErrorPrompt": "Detailed description cannot be empty or contain only whitespace characters",
        "reportContactErrorPrompt": "Contact information cannot be empty or contain only whitespace characters",
        "reportTextareaPlaceholder": "Please provide detailed reasons for reporting (required)",
        "reportNumberPlaceholder": "Please provide a valid phone number for better understanding of the situation;otherwise, it will not be processed",
        "reportReasonSource": "Please select the reason for reporting; Piracy Copyright Infringement; Medical HealthPlastic Surgery False Advertising; Cult Violation of National Policies; Pornography GamblingDrugs Pyramid Scheme; Other reasons",
        "businessNone": "None",
        "lblSimulatePageFlip": "Simulate page-flipping on a computer",
        "lblSimulatePageSlide": "Tailor to the sliding habits on a tablet",
        "suspendedForExpiredMembership": "Due to the expiration of the account member service, the access to the book has been suspended by the system",
        "suspendedForMaxReadLimit": "Due to the account reading times being exhausted, the book has been suspended by the system",
        "suspendedForReadLimit": "Due to the limit on the number of readings, the access to the book has been suspended by the system",
        "suspendedForContact": "To resume it, you can contact the author directly.",
        "expiredRedirectButton": "Explore More Books",
        "btnPhoneticReading": "Listen",
        "btnPhoneticTips": "You can listen to and read this book at the same time.",
        "articleSummary": "Article Summary",
        "articleFirst": "This is the first article.",
        "articleLast": "This is the last article.",
        "articleBack": "Back",
        "multimediaSoundOn": "Multimedia sound on",
        "multimediaSoundOff": "Multimedia sound off",
        "multimediaSoundState": "Multimedia sound state",
        "downloadRestrictionTips": "Download access for this book is restricted by the publisher.",
        "encrpytionSearchTips": "[The book has restricted access.<br\/>Please obtain permission before searching.",
        "chatbotBtnTips": "Hi~ Ask me about the book here!"
    }],
    "ols": [],
    "slideshow": [],
    "pageEditor": [],
    "flipByAudio": null,
    "downloadconfig": {
        "pdf": null,
        "isDownloadProject": false,
        "isDownloadAttach": false,
        "attachments": [],
        "hideDownloadSinglePage": false
    },
    "assistantConfig": null,
    "phoneNumber": [],
    "bookPlugin": null,
    "fliphtml5_pages": [{
        "n": ["1a.webp"],
        "t": ".\/files\/thumb\/1a.webp"
    }, {
        "n": ["1b.webp"],
        "t": ".\/files\/img\/thumb\/1b.webp"
    }, {
        "n": ["2a.webp"],
        "t": ".\/files\/img\/thumb\/2a.webp"
    }, {
        "n": ["2b.webp"],
        "t": ".\/files\/img\/thumb\/2b.webp"
    }, {
        "n": ["3a.webp"],
        "t": ".\/files\/img\/thumb\/3a.webp"
    }, {
        "n": ["3b.webp"],
        "t": ".\/files\/img\/thumb\/3b.webp"
    }, {
        "n": ["4a.webp"],
        "t": ".\/files\/img\/thumb\/4a.webp"
    }, {
        "n": ["4b.webp"],
        "t": ".\/files\/img\/thumb\/4b.webp"
    }, {
        "n": ["5a.webp"],
        "t": ".\/files\/img\/thumb\/5a.webp"
    }, {
        "n": ["5b.webp"],
        "t": ".\/files\/img\/thumb\/5b.webp"
    }, {
        "n": ["6a.webp"],
        "t": ".\/files\/img\/thumb\/6a.webp"
    }, {
        "n": ["6b.webp"],
        "t": ".\/files\/img\/thumb\/6b.webp"
    }, {
        "n": ["7a.webp"],
        "t": ".\/files\/img\/thumb\/7a.webp"
    }, {
        "n": ["7b.webp"],
        "t": ".\/files\/img\/thumb\/7b.webp"
    }, {
        "n": ["8a.webp"],
        "t": ".\/files\/img\/thumb\/8a.webp"
    }, {
        "n": ["8b.webp"],
        "t": ".\/files\/img\/thumb\/8b.webp"
    }, {
        "n": ["9a.webp"],
        "t": ".\/files\/img\/thumb\/9a.webp"
    }, {
        "n": ["9b.webp"],
        "t": ".\/files\/img\/thumb\/9b.webp"
    }, {
        "n": ["10a.webp"],
        "t": ".\/files\/img\/thumb\/10a.webp"
    }, {
        "n": ["10b.webp"],
        "t": ".\/files\/img\/thumb\/10b.webp"
    }, {
        "n": ["11a.webp"],
        "t": ".\/files\/img\/thumb\/11a.webp"
    }, {
        "n": ["11b.webp"],
        "t": ".\/files\/img\/thumb\/11b.webp"
    }, {
        "n": ["12a.webp"],
        "t": ".\/files\/img\/thumb\/12a.webp"
    }, {
        "n": ["12b.webp"],
        "t": ".\/files\/img\/thumb\/12b.webp"
    }, {
        "n": ["13a.webp"],
        "t": ".\/files\/img\/thumb\/13a.webp"
    }, {
        "n": ["13b.webp"],
        "t": ".\/files\/img\/thumb\/13b.webp"
    }, {
        "n": ["14a.webp"],
        "t": ".\/files\/img\/thumb\/14a.webp"
    }, {
        "n": ["14b.webp"],
        "t": ".\/files\/img\/thumb\/14b.webp"
    }, {
        "n": ["15a.webp"],
        "t": ".\/files\/img\/thumb\/15a.webp"
    }, {
        "n": ["15b.webp"],
        "t": ".\/files\/img\/thumb\/15b.webp"
    }, {
        "n": ["16a.webp"],
        "t": ".\/files\/img\/thumb\/16a.webp"
    }, {
        "n": ["16b.webp"],
        "t": ".\/files\/img\/thumb\/16b.webp"
    }, {
        "n": ["17a.webp"],
        "t": ".\/files\/img\/thumb\/17a.webp"
    }, {
        "n": ["17b.webp"],
        "t": ".\/files\/img\/thumb\/17b.webp"
    }],
    "downloadConfig": null,
    "fileExist": {
        "pageEditor": 0,
        "plugin": 0
    },
    "loadingConfig": {
        "loadingBackground": "#323232",
        "loadingCaptionColor": "#DDDDDD",
        "loadingCaption": "",
        "loadingCaptionFontSize": "20",
        "loadingPicture": "",
        "loadingPictureHeight": "150",
        "showLoadingGif": "Yes",
        "loadingVideo": "",
        "loadingDisplayTime": "0",
        "isEncryptionBook": false
    }
};